djangobuilder/mysite/V2oop/urls.py
from django.conf.urls import url
from . import views

# This is the controller for the app
# and directs to what methods to go to

# when it accesses /polls this is the group to go to
app_name = 'savedata'
urlpatterns = [
#debug pages
    #shows all the database items
    url(r'show/', views.show),
    #inputboxes to populate the database
    url(r'^submitform/', views.submitform.as_view(), name='submitform'),
    #index page
    url(r'^savedata/', views.IndexView.as_view(), name='savedataindex'),
    #thanks page
    url(r'^thanks/', views.thanks.as_view(), name='thanks'),
    #submitdata to database
    url(r'^submitdata/', views.submitdata, name='submitdata'),
    #working routes
    # list of tables - add/delete/modify data
    url(r'^tablelist/', views.tablelist, name='tablelist'),
    #add columns to table
    url(r'^editcolumns/', views.editcolumns, name='editcolumns'),
    #edit-columns_interaction - add data to table
    url(r'^adddata/', views.adddata, name='adddata'),  #route works
    url(r'^edittables/', views.edittables, name='edittables'),
    url(r'^createtable/', views.createtable, name='createtable'),# method to create table - no view
    url(r'^deletetable/', views.deletetable, name='deletetable'),
    url(r'^printtables/', views.printtables, name='printtables'),
    url(r'^gettablestructure/', views.gettablestructure, name='gettablestructure'),
]

djangobuilder/mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
# adding a an index and using polls as a test

    # url(r'^', include('polls.urls', namespace='polls')),
    #this is the original one
# setting the root route to be the submitform
    url(r'^', include('savedata.urls', namespace='submitform')),
    #testing with the original route

    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^savedata/', include('savedata.urls')),
    url(r'^submitform/', include('savedata.urls')),


]

djangobuilder/mysite/polls/urls.py
from django.conf.urls import url

from . import views

# This is the controller for the app
# and directs to what methods to go to

# when it accesses /polls this is the group to go to
app_name = 'polls'
urlpatterns = [
    # index view
    url(r'^$', views.IndexView.as_view(), name='index'),
    # details view
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # results view
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # vote view
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

djangobuilder/mysite/savedata/models.py
from __future__ import unicode_literals

from django.db import models


# this would be a user id store
class name(models.Model):
    name = models.CharField(max_length=200)
    #name text
    location = models.CharField(max_length=200)
    #location text
    age = models.CharField(max_length=3)
    # this is a character field defined as max length of 200
    pub_date = models.DateTimeField('date published')
    # this is an automated date stamp with the date published title
    def __str__(self):
        return self.name


# this is a model of the data going into the database

djangobuilder/mysite/savedata/forms.py
from django import forms

class NameForm(forms.Form):
    name = forms.CharField(label='Your name', max_length=100)
    location = forms.CharField(max_length=200)
    age = forms.CharField(max_length=3)
    # pub_date = forms.DateTimeField('date published')

# this is the data going in from the form

djangobuilder/mysite/savedata/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic
from . import models
from .models import name
from .forms import NameForm
from django import forms
import datetime
import json
from sqlalchemy import *
from sqlalchemy.ext.declarative import declarative_base
import sqlalchemy
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker



# things needed for sqlalchemy
eng = sqlalchemy.create_engine('postgresql+psycopg2://admin:@localhost:5432/dtabledatabase') # this is the connection to the database
meta = MetaData() # creates a meta object to hold all the things
Base = declarative_base() #declarative base class is created with this function
print("##sql alchemy initialized - version: ##  "+sqlalchemy.__version__) #sqlachemey print version




#this is a method that creates a table when hit from an ajax call
def createtable(request):
    ##*****still needs a method where it will load nontype******
    print("####create table route hit ######")
    tabletitle = request.POST.get('the_post')
    print("*******text box value is "+tabletitle)

    class tableconstructor(Base):
        __tablename__ = tabletitle

        Id = Column(String, primary_key=True)
        col1 = Column(String)
        col2 = Column(String)
        # The user-defined Car class is mapped to the Cars table. The class inherits from the declarative base class.

    Base.metadata.bind = eng
    # The declarative Base is bound to the database engine.
    Base.metadata.create_all()
    # The create_all() method creates all configured tables; in our case, there is only one table.
    Session = sessionmaker(bind=eng)
    ses = Session()
    # A session object is created.
    ses.add_all(
       [tableconstructor(Id=1, col1='Col1Empty1', col2="col2empty1"),
        tableconstructor(Id=2, col1='Col1Empty2', col2="col2empty2")])
        # With the add_all() method, we add the specified instances of Car classes to the session.
    ses.commit()
    # The changes are committed to the database with the commit() method.
    rs = ses.query(tableconstructor).all()
    # We query for all data from the Cars table. The query() method loads all instances of the Car class and its all() method returns all results represented by the query as a list.
    for item in rs:
        print (item.col1, item.col2)
    # We iterate through the result set and print two columns for all returned rows.
    return HttpResponse(
        json.dumps({"tabletitle is": tabletitle}),
        content_type="application/json"
    )





#testing methods


# We create a metadata definition of a Cars table. The table has three columns, defined with the Column class. The datatypes of columns are defined with the Integer and String classes.
def alchemytest():
    cars = Table('Cars', meta,
         Column('Id', Integer, primary_key=True),
         Column('Name', String),
         Column('Price', Integer)
    )
    print("The Name column:")
    print(cars.columns.Name)
    print(cars.c.Name)

    print("Columns: ")
    for col in cars.c:
        print (col)

    print ("Primary keys:")
    for pk in cars.primary_key:
        print (pk)

    print("The Id column:")
    print(cars.c.Id.name)
    print(cars.c.Id.type)
    print(cars.c.Id.nullable)
    print(cars.c.Id.primary_key)



#this prints all the tables in in the database
# The reflect() method automatically creates Table entries in the MetaData object for any table available in the database but not yet present in the MetaData.

def printtables(request):
    print("printtables route hit")
    meta.reflect(bind=eng)

    for table in meta.tables:
        print(table)

    return HttpResponse(
        json.dumps({"tabletitle is": table}),
        content_type="application/json"
    )



#prints out names of ITEMS in a TABLE
# The Inspector performs low-level database schema inspection. An Inspector is created with the inspect() method.

def inspectortest():
    tablename = "savedata_name"
    insp = inspect(eng)
    print(insp.get_table_names())
    #get the names of available tables
    print(insp.get_columns(tablename))
    #get columns get the names of columns in the tables
    print(insp.get_primary_keys(tablename))
    #gets teh primary keys of the
    print(insp.get_schema_names())
    #returns all the schema names

#inspectortest()




###########working methods

#this is the index view method
class IndexView(generic.ListView):
    template_name = 'savedata/savedataindex.html'
    context_object_name = 'latest_name_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return models.name.objects.order_by('-pub_date')[:5]



#this is the submit form view
class submitform(generic.ListView):
    template_name = 'savedata/submitform.html'
    context_object_name = 'latest_name_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return models.name.objects.order_by('-pub_date')[:5]



# submitform route method sends the data to the database and then
def submitdata(request):
    print("submitdata accessed")
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        print("=== post hit")
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        print("after post request if hit")
        # check whether it's valid:
        if form.is_valid():
            name = form.cleaned_data["name"]
            age = form.cleaned_data["age"]
            location = form.cleaned_data["location"]
            # date = form.cleaned_data["pub_date"]
            print(location)
            print(age)
            print(name)
            # print(date)
            #creating a my var object to save the parameters
            myVar = models.name()
            #attaching input fields to objects
            myVar.name = name
            myVar.age = age
            myVar.location = location
            myVar.pub_date = datetime.datetime.now()
            myVar.save()

            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:


            return HttpResponseRedirect('/adddata/')
        # else:
        #     print(dir(form.errors))
     # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()

    return render(request, 'savedata/adddata.html', {'form': form})



class thanks(generic.ListView):
    template_name = 'savedata/thanks.html'
    # context_object_name = 'latest_name_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return models.name.objects.order_by('-pub_date')[:5]





###def based view - this works with the regular routes

def show(request):
    thing = name.objects.all()
    context = {'thing': thing}  #this is a dictonary
    print(context)
    return render(request, 'savedata/show.html', context)




def edittables(request):
    print("edit route hit")
    thing = name.objects.all() #query the database
    context = {'thing': thing}  #this is a dictonary
    print(context)
    return render(request, 'savedata/table-edit.html', context)





def editcolumns(request):
    print("editcolumns route hit")
    #set default table
    #set table to table selected
    #get contents of table
    #render page

    rendertable = "savedata_name"
    # rendertable = request.POST.get('buttonidholder')

    thing = name.objects.all() #query the database



    context = {'thing': thing}  #this is a dictonary
    print(context)
    return render(request, 'savedata/edit-columns.html', context)





def gettablestructure(request):
    tabletoview = "savedata_name"
    # Create MetaData instance
    metadata = MetaData(eng, reflect=True)
    print(metadata.tables)
    # saves the data from the table in question
    ex_table = metadata.tables[tabletoview]


    for t in metadata.tables[tabletoview]:
        print(t.name)


    return HttpResponse(
        json.dumps({"tabletitle is": "test"}),
        content_type="application/json"
    )






#shows tables in database on page tablelist

def tablelist(request):
    print("tablelist route hit")
    tablelistarray = []
    meta.reflect(bind=eng)

    for table in meta.tables:
        tablelistarray.insert(0,table)
        print(table)
        print('Final array:', tablelistarray)

    context = {'thing': tablelistarray}
    print(context)
    return render(request, 'savedata/table-list.html', context)




#delete table route needs to be changed to get tables by ids
def deletetable(request):
    print("delete route hit")
    tabletodelete = request.POST.get('buttonidholder')
    context = { 'thing': tabletodelete }  #this is a dictonary
    print("table to delete is")
    print(tabletodelete) #sanity checking

    # delete the corresponding table
    table_name = tabletodelete
    table = Table(table_name, meta)
    if table.exists(bind=eng):
        table.drop(bind=eng)
        return render(request, 'savedata/table-list.html', context)

    return render(request, 'savedata/table-list.html', context)





#route which submits data to a table
def adddata(request):
    print("adddata route hit")

    #renders table page with data from database
    # going to use this as a test currently
    #***Need to add a variable to hold the table name
    thing = name.objects.all() #query the database (this needs to be changed to get the ids and names of all the tables)
    # title = name.objects.all() #this needs to be changed to title of the database
    context = { 'thing': thing,
                'title': "Title passed in from selector",
                }  #this is a dictonary
    print(context)
    return render(request, 'savedata/adddata.html', context)



#simple redirect route
def redirect(request):

djangobuilder/mysite/savedata/templates/savedata/adddata.html
{%  load static %}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>DTables </title>
    <link href="{% static 'savedata/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'savedata/font-awesome/css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'savedata/css/plugins/dataTables/datatables.min.css' %}" rel="stylesheet">
    <link href="{% static 'savedata/css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'savedata/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'savedata/css/main.css' %}" rel="stylesheet">

</head>

<body>

    <div id="wrapper">

    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
        <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
	    	<ul class="nav navbar-top-links navbar-left" style="margin-left: 20px;">
		    	<li>
		    		<a class="navbar-brand" href="table-list.html">Table List</a>
		    	</li>
	    	</ul>

            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <a href="login.html">
                        <i class="fa fa-sign-out"></i> Logout
                    </a>
                </li>
            </ul>

        </nav>
        </div>
        <div class="row">
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                        <h1>{{ title }}</h1>
                        <h2>Update Table Data - Edit Table Page - Shows data and can edit data</h2>
                </div>
            </div>



                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>Table Data</h5>
                            <div class="ibox-tools">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="fa fa-wrench"></i>
                                </a>
                                <a class="close-link">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                        </div>




                    <div class="ibox-content">

                      <div class="table-responsive">

						             <div class="dataTables_info" id="DataTables_Table_0_info" role="status" aria-live="polite" style="padding-bottom: 8px;">Showing 1 to 14 of 14 entries</div>

                             <table class="table table-striped table-bordered table-hover dataTables-example" >

                                <thead>

                                  <tr>
                                      <th>Name</th>
                                      <th>Age</th>
                                      <th>Location</th>
                                      <th>Pubdate</th>
                                  </tr>

                                </thead>

                    <tbody>

                    <tr class="gradeC">
                    </tr>



<!-- this is the input boxes -->
                    <tr class="gradeC">
                     <form action="/submitdata/" method="post">
  	                 <td><input id="id_name" type="text" name="name" value="{{ name }}"></td>
  	                 <td><input id="id_age" type="text" name="age" value="{{ age }}"></td>
  	                 <td><input id="id_location" type="text" name="location" value="{{ location }}">
  	                    <td>Pub data is automatic

                        <!-- <input id="id_location" type="text" name="location" value="{{ location }}"> --></td>
<!--                    <td><input type="email" placeholder="Pub Date" class="form-control"></td>
 -->
                        <td style="vertical-align: middle;">
	                       <!--  <button type="button" class="btn btn-xs btn-primary" style="margin-bottom: 0;">Confirm</button>
	                        <button type="button" class="btn btn-xs btn-default" style="margin-bottom: 0;">Cancel</button> -->

                          <input type="submit" value="OK">

                          {% csrf_token %}
                          </form>
	                    </td>
                    </tr>



<!-- this is the list of items and buttons to change them -->

                      <tr class="gradeC">

                    {% for item in thing %}

                        <td>{{ item.name }}</td>
                        <td>{{ item.age }}</td>
                        <td>{{ item.location }}</td>
                        <td>{{ item.pub_date }}</td>
                          <td>
                            <button type="button" id="{{ item.id }}" class=" editcolumnsbutton btn btn-xs btn-success" style="margin-bottom: 0;">Edit Columns</button>

                            <button type="button" id="{{ item.id }}" class="editdatabutton btn btn-xs btn-primary" style="margin-bottom: 0;">Edit Data</button>

                            <button type="button" id="{{ item.id }}" class=" deletebutton btn btn-xs btn-primary" style="margin-bottom: 0;">Delete Table</button>
                        </td>
                      </tr>
                    {% endfor %}

                    </tr>

                    <tr class="gradeC">
	                    <td>Cart_Product_Id</td>
	                    <td>Auto Increment</td>
	                    <td>No</td>
	                    <td>32</td>
	                    <td></td>

                        <td>
	                        <button type="button" class="btn btn-xs btn-success" style="margin-bottom: 0;">Edit</button>
	                        <button type="button" class="btn btn-xs btn-default" style="margin-bottom: 0;">Delete</button>
	                    </td>

                    </tr>


                    </tbody>
                    </table>
                        </div>

                    </div>
                </div>
            </div>
            </div>
        </div>

        </div>
        </div>



    <!-- Mainly scripts -->
    <script src="{% static 'savedata/js/jquery-2.1.1.js' %}"></script>
    <script src="{% static 'savedata/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'savedata/js/addons.js' %}"></script>



    <!-- Custom and plugin javascript -->

</body>

</html>

djangobuilder/mysite/savedata/templates/savedata/edit-columns.html
{%  load static %}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>DTables</title>


    <link href="{% static 'savedata/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'savedata/font-awesome/css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'savedata/css/plugins/dataTables/datatables.min.css' %}" rel="stylesheet">
    <link href="{% static 'savedata/css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'savedata/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'savedata/css/main.css' %}" rel="stylesheet">



</head>

<body>

    <div id="wrapper">

    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
        <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
	    	<ul class="nav navbar-top-links navbar-left" style="margin-left: 20px;">
		    	<li>
		    		<a class="navbar-brand" href="table-list.html">Table List</a>
		    	</li>
	    	</ul>

            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <a href="login.html">
                        <i class="fa fa-sign-out"></i> Logout
                    </a>
                </li>
            </ul>

        </nav>
        </div>
        <div class="row">
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <h1>[Table Name] Columns</h1>
                    <h2>Update Table Columns</h2>
                </div>
            </div>



                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>Column List</h5>
                            <div class="ibox-tools">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="fa fa-wrench"></i>
                                </a>
                                <a class="close-link">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                        </div>



                        <div class="ibox-content">
                            <form role="form" class="form-inline">

 <input type="text" name="fname" placeholder="Column Name"><br>
	                              <button type="button" class="btn btn-w-m btn-success" style="margin-bottom: 0;">Add Column</button>

                            </form>

                            <div class="ibox-content">
                                Select table
                            <select>
                                {% for item in thing %}
                                <option value={{ item }}>{{ item }}</option>
                                {% endfor %}
                             </select>
                            </div>
                        </div>




                    <div class="ibox-content">

                    <div class="table-responsive">
						<div class="dataTables_info" id="DataTables_Table_0_info" role="status" aria-live="polite" style="padding-bottom: 8px;">Showing 1 to 14 of 14 entries</div>

                    <table class="table table-striped table-bordered table-hover dataTables-example" >
                    <thead>

                    <!--this needs to be the columns-->

                    <tr>
                        {% for item in thing %}
	                        <th>{{ item }}
                                <button type="button" id="{{ item }}" class=" deletecolumnbutton btn btn-xs btn-success" style="margin-bottom: 0;">Delete col</button>
</th>
                        {% endfor %}
                    </tr>



                    </thead>
                    <tbody>
                    <tr class="gradeC">
	                    <td>1</td>
	                    <td>Id</td>
	                    <td>Auto Increment</td>
	                    <td>No</td>
	                    <td>32</td>
	                    <td></td>
                        <td>
	                        <button type="button" class="btn btn-xs btn-success" style="margin-bottom: 0;">Edit</button>
	                        <button type="button" class="btn btn-xs btn-default" style="margin-bottom: 0;">Delete</button>
	                    </td>
                    </tr>

                    <tr class="gradeC">
	                    <td>2</td>
	                    <td>Active</td>
	                    <td>Auto Increment</td>
	                    <td>No</td>
	                    <td>32</td>
	                    <td></td>
                        <td>
	                        <button type="button" class="btn btn-xs btn-success" style="margin-bottom: 0;">Edit</button>
	                        <button type="button" class="btn btn-xs btn-default" style="margin-bottom: 0;">Delete</button>
	                    </td>
                    </tr>

                    <tr class="gradeC">
	                    <td>3</td>
	                    <td>Cart_Product_Id</td>
	                    <td>Auto Increment</td>
	                    <td>No</td>
	                    <td>32</td>
	                    <td></td>
                        <td>
	                        <button type="button" class="btn btn-xs btn-success" style="margin-bottom: 0;">Edit</button>
	                        <button type="button" class="btn btn-xs btn-default" style="margin-bottom: 0;">Delete</button>
	                    </td>
                    </tr>


                    </tbody>
                    </table>
                        </div>

                    </div>
                </div>
            </div>
            </div>
        </div>

        </div>
        </div>



    <!-- Mainly scripts -->
    <script src="{% static 'savedata/js/jquery-2.1.1.js' %}"></script>
    <script src="{% static 'savedata/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'savedata/js/addons.js' %}"></script>



    <!-- Custom and plugin javascript -->

</body>

</html>

djangobuilder/mysite/savedata/templates/savedata/savedataindex.html
<h1>This is an index page at /savedataindex.html </h1>
need to create a form on this page and a list

{% if latest_name_list %}
    <ul>
    {% for name in name_question_list %}
      <li><a href="{% url 'polls:detail' name.id %}">{{ name.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>data is not available or not populating correctly - hitting the else statement</p>
{% endif %}

djangobuilder/mysite/savedata/templates/savedata/show.html
this is the def based view
  <h1>Users Table</h1>

<table>

    <tr>
      <th>Id</th>
        <th>First Name</th>
        <th>Last Name</th>
    </tr>

    {% for item in thing %}
    <tr>
      <td>{{ item.name }}</td>
        <td>{{ item.age }}</td>
        <td>{{ item.location }}</td>
    </tr>
    {% endfor %}
</table>

djangobuilder/mysite/savedata/templates/savedata/submitform.html
<!-- the submitform will be used as the index and will have the
submit form as well as the database table display
-->


<!-- Submit form section -->
 <form action="/submitdata/" method="post">
    <label for="name">Name: </label>
    <input id="id_name" type="text" name="name" value="{{ name }}">

    <label for="age">Age:</label>
    <input id="id_age" type="text" name="age" value="{{ age }}">

    <label for="location">Location:</label>
    <input id="id_location" type="text" name="location" value="{{ location }}">

    <input type="submit" value="OK">

{% csrf_token %}
</form>





<!-- this is the code for error handling -->

  {% if form.errors %}
    <div class="alert alert-error">
      <h4>Please fix the following errors</h4>
      <ul>
        {% for field in form %}
          {% if field.errors %}
            {% for error in field.errors %}
              <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
            {% endfor %}
          {% endif %}
        {% endfor %}
      </ul>
      {% if form.non_field_errors %}
        {{ form.non_field_errors }}
      {% endif %}
    </div>
  {% endif %}

djangobuilder/mysite/savedata/templates/savedata/thanks.html
this is the thanks page,


so yea thanks man



<form action="/submitformroute/">
    <input type="submit" value="Go back submit page">
</form>